[project]
name = "flitzis-looper"
version = "7.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11,<3.12"
dependencies = [
    "demucs>=4.0.1",
    "madmom",
    "matplotlib>=3.10.7",
    "numpy>=2.3.5",
    "pedalboard>=0.9.19",
    "pyo; sys_platform == 'win32'",
    "pyo @ git+https://github.com/openSUSE-Python/pyo.git@gcc15-build; sys_platform != 'win32'",
    "setuptools>=80.9.0",
    "soundfile>=0.13.1",
    "torch>=2.9.1",
    "torchaudio>=2.9.1",
]

[tool.uv.sources]
madmom = { git = "https://github.com/CPJKU/madmom.git" }

[tool.uv.extra-build-dependencies]
madmom = ["Cython", "numpy"]

[dependency-groups]
dev = [
    "mypy>=1.19.0",
    "pytest>=9.0.2",
    "ruff>=0.14.8",
]

[tool.ruff]
extend = "ruff_defaults.toml"

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
addopts = [
    "--verbose",
    "--tb=short",
    "--strict-markers",
    "--strict-config"
]
markers = [
    "unit: Unit tests",
    "integration: Integration tests",
    "slow: Slow running tests"
]
